package:
  name: java-1.8.0-openjdk-el9-aarch64
  version: 1.8.0.452b9

source:
  - url: https://download.rockylinux.org/vault/rocky/9.5/AppStream/aarch64/os/Packages/j/java-1.8.0-openjdk-1.8.0.452.b09-2.el9.aarch64.rpm
    sha256: e50b68e3a603156ca1375c0dd49c14651dc5b3d33cc41a98bfe6918e4f8e6271
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and aarch64)]
  number: {{ build_number }}
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.34.*
  host:
    - copy-jdk-configs-el9-aarch64 >=4.0 *_{{ build_number }}
    - javapackages-filesystem-el9-aarch64 >=6.0.0 *_{{ build_number }}
    - ca-certificates
    - alsa-lib
    - xorg-libx11
    - xorg-libxext
    - xorg-libxi
    - xorg-libxrender
    - xorg-libxtst
  run:
    - sysroot_linux-aarch64 2.34.*
    - copy-jdk-configs-el9-aarch64 >=4.0 *_{{ build_number }}
    - javapackages-filesystem-el9-aarch64 >=6.0.0 *_{{ build_number }}
    - ca-certificates
    - alsa-lib
    - xorg-libx11
    - xorg-libxext
    - xorg-libxi
    - xorg-libxrender
    - xorg-libxtst

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el9-linux-gnu/sysroot/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.452.b09-2.el9.aarch64/jre/lib/aarch64/libjawt.so

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib
  license_family: Other
  summary: (CDT) OpenJDK 8 Runtime Environment
  description: |
    The OpenJDK 8 runtime environment.
  doc_url: http://openjdk.java.net/
  dev_url: http://openjdk.java.net/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
