package:
  name: kmod-el9-aarch64
  version: 28

source:
  - url: https://download.rockylinux.org/vault/rocky/9.5/BaseOS/aarch64/os/Packages/k/kmod-28-10.el9.aarch64.rpm
    sha256: 6d659c5ad55e44c6dd9a73a9e374e1b7b6f38acf8932459e28a8909a3039d3de
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and aarch64)]
  number: {{ build_number }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-aarch64 2.34.*
  host:
  run:
    - sysroot_linux-aarch64 2.34.*
    - kmod-libs-el9-aarch64 ==28 *_{{ build_number }}
    - libgcc-ng
    - libxcrypt-el9-aarch64 >=4.4.18 *_{{ build_number }}
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/aarch64-conda_el9-linux-gnu/sysroot/usr/sbin/modinfo

about:
  home: https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git
  license: LGPL-2.1-only  # GPLv2+
  license_family: GPL2
  license_file:
    - COPYING
  summary: (CDT) Linux kernel module management utilities
  description: |
    The kmod package provides various programs needed for automatic
    loading and unloading of modules under 2.6, 3.x, and later kernels, as well
    as other module management programs. Device drivers and filesystems are two
    examples of loaded and unloaded modules.
  doc_url: https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git
  dev_url: https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
